2025-05-25 22:15:33,713 ERROR: Exception on / [GET] [in C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\app.py", line 352, in landing
    return render_template('landing.html')
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\templates\landing.html", line 17, in top-level template code
    <a href="{{ url_for('admin') }}" class="btn-secondary">
    ^^^^^^^^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin'. Did you mean 'landing' instead?
2025-05-25 22:17:28,551 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:17:28,551 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:17:39,934 ERROR: Exception on /admin/users [GET] [in C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\Administrator\Desktop\financial - Copy (2)\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'login_manager'
2025-05-25 22:21:36,830 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:21:36,851 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:21:56,771 WARNING: Failed login attempt for username: Vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-25 22:24:14,276 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:24:14,277 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:26:29,890 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:26:29,890 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:32:42,078 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:32:42,080 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:35:19,183 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:35:19,184 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:44:56,261 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:44:56,262 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:52:41,116 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:52:41,129 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:53:19,734 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-25 22:54:38,146 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-25 22:54:38,149 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-25 22:54:56,099 WARNING: Failed login attempt for username: Jeody [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-26 23:05:26,704 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-26 23:05:26,707 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-26 23:06:08,095 INFO: User Jeody logged in successfully as user [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:382]
2025-05-26 23:07:01,394 INFO: Generated 8 insights for user 2 [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:612]
2025-05-26 23:10:41,223 INFO: User Jeody logged in successfully as user [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:382]
2025-05-27 10:25:06,027 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-27 10:25:06,123 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-27 10:26:14,955 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-27 10:26:24,278 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-27 10:26:52,344 INFO: User Jeody logged in successfully as user [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:382]
2025-05-27 10:27:21,635 WARNING: Failed login attempt for username: Vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-27 10:27:28,409 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-27 10:29:12,237 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-27 10:29:12,238 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-27 10:30:24,480 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
2025-05-27 10:34:10,278 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-27 10:34:10,279 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:343]
2025-05-27 10:38:44,963 INFO: Financial application startup [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:27]
2025-05-27 10:39:26,416 WARNING: Failed login attempt for username: vincey [in C:\Users\Administrator\Desktop\financial - Copy (2)\app.py:388]
